name: Comment PR new module release when pr committed and labeled/unlabeled

on: workflow_dispatch

jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
      - name: Setup azdev
        env:
          TITLE: "hello there"
        run: |
          pr_title=$(echo "$TITLE" | grep -oP '[{\[][^}\]]+[}\]]' | sed 's/{\|}\|\[\|\]//g')
          echo "pr_title=$pr_title" >> $GITHUB_ENV
          echo "message=$(echo 'Suggested version: 1.0.0b1 for preview release and 1.0.0 for stable release')" >> $GITHUB_ENV
